# Generated by Django 3.1.3 on 2021-01-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_cost',
            old_name='body',
            new_name='body_cost',
        ),
    ]
