# Generated by Django 3.1.3 on 2020-12-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regiter_extra_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_profile', models.ImageField(blank=True, upload_to='profile_pics')),
                ('date', models.DateField()),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Famale')], max_length=300)),
            ],
        ),
    ]
