# Generated by Django 3.1.3 on 2020-12-20 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regiter_extra_model',
            old_name='picture_profile',
            new_name='image',
        ),
        migrations.AddField(
            model_name='regiter_extra_model',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regiter_extra_model',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
