# Generated by Django 3.1.3 on 2020-12-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201220_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiter_extra_model',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
