# Generated by Django 3.1.3 on 2020-12-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201226_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiter_extra_model',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Famale')], max_length=300, null=True),
        ),
    ]
