# Generated by Django 3.1.3 on 2020-12-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20201228_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiter_extra_model',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/def.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
