# Generated by Django 3.1.3 on 2020-12-07 14:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_newreviewtoadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newreviewtoadmin',
            name='Reviews',
        ),
        migrations.AddField(
            model_name='newreviewtoadmin',
            name='text',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='itemReviewToAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=300)),
                ('new_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.newreviewtoadmin')),
            ],
        ),
    ]
