# Generated by Django 3.1.3 on 2020-12-14 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0007_auto_20201207_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemreviewtoadmin',
            name='text',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='newreviewtoadmin',
            name='text',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
