# Generated by Django 3.1.3 on 2020-12-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0013_auto_20201217_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories_model',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stories_model',
            name='text',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
