# Generated by Django 3.1.3 on 2020-12-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0015_picture_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='regiter_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Famale')], max_length=300)),
                ('Picture', models.ImageField(blank=True, upload_to='profile_pics')),
            ],
        ),
    ]
