# Generated by Django 3.1.3 on 2020-12-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0019_auto_20201220_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip_model',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
