# Generated by Django 3.1.3 on 2020-12-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0020_tip_model_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QA_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('text', models.TextField(max_length=5000, null=True)),
                ('release_date', models.DateField(null=True)),
            ],
        ),
    ]
