# Generated by Django 3.1.3 on 2021-01-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0034_auto_20201228_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreviewtoadmin',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
