# Generated by Django 3.1.3 on 2021-01-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210104_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='aproved',
            field=models.BooleanField(null=True),
        ),
    ]
