# Generated by Django 3.1.3 on 2021-01-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_payment_aproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
