# Generated by Django 3.1.3 on 2021-01-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='aproved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
