# Generated by Django 3.1.3 on 2021-01-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210106_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='payment_date',
        ),
    ]
