# Generated by Django 3.1.3 on 2021-01-09 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20210107_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_first_question_model',
            name='Medication_sensitivity',
        ),
        migrations.RemoveField(
            model_name='chat_first_question_model',
            name='taking_medication',
        ),
    ]
