# Generated by Django 3.1.3 on 2020-12-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201225_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regiter_extra_model',
            old_name='user',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='regiter_extra_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
