# Generated by Django 3.1.3 on 2020-12-27 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_auto_20201227_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiter_extra_model',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regiter_extra_model', to=settings.AUTH_USER_MODEL),
        ),
    ]
