# Generated by Django 3.1.3 on 2020-12-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201228_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiter_extra_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
