# Generated by Django 3.1.3 on 2020-12-28 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_auto_20201228_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiter_extra_model',
            name='image',
            field=models.ImageField(blank=True, default='def.jpg', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='regiter_extra_model',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
