# Generated by Django 3.1.3 on 2020-11-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20201129_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_pic',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio_site',
            new_name='portfolio',
        ),
    ]
