# Generated by Django 3.1.3 on 2020-12-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_activation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
    ]
