# Generated by Django 3.1.3 on 2020-12-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_auto_20201214_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemreviewtoadmin',
            name='new_review',
        ),
    ]
