# Generated by Django 3.1.3 on 2020-12-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0011_remove_itemreviewtoadmin_new_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewReviewToAdmin',
        ),
        migrations.AddField(
            model_name='itemreviewtoadmin',
            name='from_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
