# Generated by Django 3.1.3 on 2020-12-17 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_auto_20201215_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='stories_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254, null=True)),
                ('subject', models.CharField(max_length=300)),
                ('text', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='picture',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='picture_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.user'),
        ),
        migrations.AlterField(
            model_name='itemreviewtoadmin',
            name='text',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
