# Generated by Django 3.1.3 on 2020-12-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_auto_20201217_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='picture_people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_profile', models.ImageField(blank=True, upload_to='profile_pics')),
            ],
        ),
    ]
