# Generated by Django 3.1.3 on 2020-12-25 11:06

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0022_stand_up_video1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stand_up',
            name='video1',
        ),
        migrations.AlterField(
            model_name='motivation',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AlterField(
            model_name='stand_up',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
