# Generated by Django 3.1.3 on 2020-12-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0023_auto_20201225_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivation',
            name='subject',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='subject',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='stand_up',
            name='subject',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='itemreviewtoadmin',
            name='subject',
            field=models.CharField(max_length=30),
        ),
    ]
