# Generated by Django 3.1.3 on 2020-12-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0025_auto_20201225_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_first_question_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taking_medication', models.CharField(max_length=5000)),
                ('Medication_sensitivity', models.CharField(max_length=5000)),
                ('Corona_feeling', models.CharField(max_length=5000)),
                ('if_psychologist', models.CharField(max_length=5000)),
                ('about_yourself', models.CharField(max_length=5000)),
            ],
        ),
    ]
