# Generated by Django 3.1.3 on 2020-12-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0026_chat_first_question_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_first_question_model',
            name='fell',
            field=models.CharField(choices=[('good', 'GOOD'), ('bad', 'Bad'), ('excellent', 'Excellent'), ('okay', 'Okay')], max_length=9, null=True),
        ),
    ]
