# Generated by Django 3.1.3 on 2020-12-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0029_chat_first_question_model_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_first_question_model',
            old_name='user',
            new_name='regiter_extra_model',
        ),
    ]
