# Generated by Django 3.1.3 on 2020-12-27 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0030_auto_20201226_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_first_question_model',
            old_name='regiter_extra_model',
            new_name='user',
        ),
    ]
