# Generated by Django 3.1.3 on 2020-12-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0032_auto_20201227_1033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='picture_people',
        ),
        migrations.AlterField(
            model_name='qa_model',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
    ]
