# Generated by Django 3.1.3 on 2020-12-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0033_auto_20201228_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories_model',
            name='release_date',
        ),
        migrations.AlterField(
            model_name='qa_model',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tip_model',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
