# Generated by Django 3.1.3 on 2021-01-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0037_auto_20210104_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QA_model',
        ),
        migrations.DeleteModel(
            name='tip_model',
        ),
    ]
