# Generated by Django 3.1.3 on 2021-01-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0038_auto_20210104_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='motivation',
        ),
        migrations.DeleteModel(
            name='sport',
        ),
        migrations.DeleteModel(
            name='stand_up',
        ),
    ]
