# Generated by Django 3.1.3 on 2021-01-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0039_auto_20210104_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreviewtoadmin',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
